const solve = (A) => {
  let countA = 0;
  let pairs = 0;
  for (let x of A) {
    if (x === "A") {
      countA++;
    } else if (x === "G") {
      pairs += countA;
    }
  }
  return parseInt(pairs);
};

console.log(
  solve(
    "AAGBGGAGAGAGGLRAAAAZGQAGGGAAPPAGGGYAAZGLZGAGAAOAGAGPKSKOGMPGAIUADAAATKGGGAUGIGMTKAFAGAAAUSBGGGISAGMAGOGGKGLRGGGJDAZKIGAAAGZGATAAAAGAAAGGAYGCARGNGGAGALAAXAUPQUDRGXANAGGAAUAUKAAAAANGUGABNAAATGGAGNKIFGGOORJGYAEASGAAATGUGGGBAGGGYGAJXAAAAAGNOAMGSIAEAGRIGTAGGGGGKMAJGCSAGGGAZQGAGCGGAGRMYDAGAAAAFQAGAJAGGMGXLGGGABTGETAMUOAUAAAGSZAGLGGSYAAJPZCAEGGAAAGGCGAGRFJGAYAAGGCRAAAGGZGEULPAPXZGAAGGNFLAARRAQNXGGGGAGAGASALAZUQGGDJAYNAYLAGGGGAAAKSGAADGAGCAAGGGBGAAIZAGOGIAGOLGGQTGGGAAGQATPZGSGGQJALIAEJUUSAAAGAAAEAPQPAUAAAAGTAAGAGYNZGGNYAAGAJABGGAGGLARGEGKASFMPEAOGOUFAGGAAMEABAGPTZAGAGYGZGUAGGACGXAFGGAGRLAAPQGMOFKGAMAQAGYUAGAXANGCGAAGGGAAGPZGAOGSIGGAGAGKJAUSUAAGGGGEAQGATGXGGOGYAGYLQGGAAGFGGAGGGZGQAAAAAGAAUAKAMYJXCGGIDQQCAGGSJCXDFAGIYGAAASALGYGUYGAGYICANAKAAOGQPGGNAGGAGGICAGAAANAGESFGGAGLBSFAAAAMMATAUINPAGGTGDSGAAAMCGAFAQBFJGPYGAEAFAOAGAFATGABGJLAGLAYIGSQAG"
  )
);
